=== geetheshtg/NCP/proj_xml/proj.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT alumni-system (alumnus)>
<!ATTLIST alumni-system
  xmlns CDATA #FIXED ''>

<!ELEMENT alumnus (first-name,last-name,username,position,company,skillset)>
<!ATTLIST alumnus
  xmlns CDATA #FIXED ''>

<!ELEMENT first-name (#PCDATA)>
<!ATTLIST first-name
  xmlns CDATA #FIXED ''>
  
<!ELEMENT last-name (#PCDATA)>
<!ATTLIST last-name
  xmlns CDATA #FIXED ''>

<!ELEMENT username (#PCDATA)>
<!ATTLIST username
  xmlns CDATA #FIXED ''>

<!ELEMENT position (#PCDATA)>
<!ATTLIST position
  xmlns CDATA #FIXED ''>

<!ELEMENT company (#PCDATA)>
<!ATTLIST company
  xmlns CDATA #FIXED ''>

<!ELEMENT skillset (#PCDATA)>
<!ATTLIST skillset
  xmlns CDATA #FIXED ''>

=== geetheshtg/NCP/proj_xml/proj.xml
<?xml version="1.0"?>
<!DOCTYPE alumni-system SYSTEM "proj.dtd">
<?xml-stylesheet type="text/xsl" href="proj.xsl" ?>

<alumni-system  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="proj.xsd">

  <alumnus>
    <first-name> Geethesh </first-name>
    <last-name> TG </last-name>
    <username> tggeethesh </username>
    <position> Principal Engineer </position>
    <company> Versa Networks </company>
    <skillset> Deep Learning </skillset>
  </alumnus>
  
</alumni-system>
